/**
 * @file lora_service.h
 * @brief LoRa communication service (Layer 6).
 * @details Service-level wrapper around MAC layer, providing clean interface
 *          for app and device_fsm. Encapsulates LoRa network operations including:
 *          - Heartbeat transmission (periodic keepalive)
 *          - Alarm/event uplink notifications
 *          - Join/exit network orchestration
 *          - Gateway connectivity status queries
 *          - Power management coordination
 *
 *          This service consolidates all LoRa-related operations previously split
 *          between app_main direct MAC calls and heartbeat_service.
 *
 * @author EMIC Team
 * @version 1.0.0
 * @date 2026-01-14
 */

#ifndef LORA_SERVICE_H
#define LORA_SERVICE_H

#include <stdint.h>

/**
 * @brief LoRa service event types.
 * @details Events generated by MAC layer and exposed to application through service API.
 */
typedef enum
{
    LORA_EVENT_NONE = 0,
    LORA_EVENT_HEARTBEAT_DUE = 1,
    LORA_EVENT_REMOTE_ALARM = 2,
    LORA_EVENT_GW_LOST = 3,
    LORA_EVENT_REMOTE_ALARM_STOP = 4,
    LORA_EVENT_REMOTE_SILENCE = 5,
    LORA_EVENT_JOIN_ACCEPTED = 6,
    LORA_EVENT_ENTER_OPERATION = 7,
    LORA_EVENT_EXIT_GW = 8,
    LORA_EVENT_TEST_ED = 9
} lora_event_t;

/**
 * @brief Initialize LoRa service.
 * @details Initializes MAC layer, loads provisioned keys/IDs from NV storage.
 *          Must be called once during system startup before any other lora_service calls.
 */
void lora_service_init(void);

/**
 * @brief Run LoRa service state machine (main polling function).
 * @details Must be called from main loop. Processes:
 *          - CAD paging schedule
 *          - RX windows
 *          - TX queues and retransmissions
 *          - Incoming frame processing
 * @note Called from main loop context (not ISR).
 */
void lora_service_run(void);

/**
 * @brief Notify service of RTC constant-period tick (called every 0.5s).
 * @details Updates timing for CAD schedule, heartbeat, gateway loss detection, join timeout.
 * @note Called from main context (not ISR).
 */
void lora_service_on_rtc_tick(void);

/**
 * @brief Poll next pending LoRa event (if any).
 * @return lora_event_t Event code (LORA_EVENT_NONE if no event pending).
 * @note Called from main loop after lora_service_run().
 */
lora_event_t lora_service_poll_event(void);

/**
 * @brief Request heartbeat transmission.
 * @details Triggers uplink transmission of heartbeat frame when radio is ready.
 *          Typically called by device_fsm in response to LORA_EVENT_HEARTBEAT_DUE.
 * @note Replaces heartbeat_service_send() from previous design.
 */
void lora_service_send_heartbeat(void);

/**
 * @brief Notify service of local smoke alarm detection.
 * @details Triggers uplink transmission of ALARM frame when radio is ready.
 * @note Called by device_fsm when local smoke sensor detects fire.
 */
void lora_service_notify_alarm(void);

/**
 * @brief Notify service that local smoke alarm has been cleared.
 * @details Triggers uplink transmission of ALARM_STOP frame.
 * @note Called by device_fsm when local smoke sensor clears or user stops test.
 */
void lora_service_notify_alarm_cleared(void);

/**
 * @brief Request service to initiate Join Mode (user-triggered join request).
 * @details Triggers repeated JoinRequest transmissions with RX windows.
 * @note Called by device_fsm when user presses join button sequence.
 */
void lora_service_request_join(void);

/**
 * @brief Request service to exit the network (send EXIT frame and leave).
 * @details Triggers uplink EXIT frame transmission.
 * @note Called by device_fsm when user requests network exit.
 */
void lora_service_request_exit(void);

/**
 * @brief Enable/disable Join Mode (user-initiated connection setup).
 * @param on 1 to enable Join Mode, 0 to disable.
 * @details When enabled (and not joined), MAC sends JoinRequest every ~1s and opens
 *          RX window after each TX. Disabled automatically upon JOIN_ACCEPTED event.
 * @note Called by device_fsm to control join mode state.
 */
void lora_service_set_join_mode(uint8_t on);

/**
 * @brief Check if node has successfully joined the network.
 * @return 1 if joined (JoinAccept or EnterOperation received), 0 otherwise.
 * @note Used by app and device_fsm to determine operational state.
 */
uint8_t lora_service_is_joined(void);

/**
 * @brief Check if gateway is currently online.
 * @return 1 if online (valid GW_BEACON received within timeout), 0 otherwise.
 * @note Online means a valid GW_BEACON has been received within configured timeout.
 */
uint8_t lora_service_is_gw_online(void);

/**
 * @brief Get time (in seconds) since last gateway beacon was received.
 * @return Age in seconds (0xFFFFFFFF if no beacon ever received).
 * @note Used by app to determine offline status and update alarm service.
 */
uint32_t lora_service_get_gw_age_s(void);

/**
 * @brief Check if RTC time has been synchronized with gateway.
 * @return 1 if RTC time is synchronized (from GW TIME_SYNC message), 0 otherwise.
 * @note Used by device_fsm to validate time-based operations.
 */
uint8_t lora_service_is_rtc_synced(void);

/**
 * @brief Check if radio is currently busy (CAD/RX/TX in progress).
 * @return 1 if radio busy, 0 if idle.
 * @note Used by power_service to decide HALT vs STOP power mode.
 */
uint8_t lora_service_is_busy(void);

/**
 * @brief Put radio into sleep mode (warm-start ready).
 * @details Called when transitioning to STOP power mode; radio will wake
 *          automatically on next CAD/RX/TX request.
 * @note Called by power_service before entering low-power mode.
 */
void lora_service_sleep(void);

#endif /* LORA_SERVICE_H */
