/*
 * File: hal_spi.c
 * Description: SPI Hardware Abstraction Layer for SX1262
 * Module: CSI20 (Serial Array Unit, Channel 0)
 * Speed: 2 MHz (8MHz MCU / 4 prescaler)
 * 
 * Pin assignments (from Smart Config Pin.h):
 * - RADIO_SCK_PIN (P1.5):  Clock
 * - RADIO_MOSI_PIN (P1.3): Master Out, Slave In (SO20)
 * - RADIO_MISO_PIN (P1.4): Master In, Slave Out (SI20)
 * - RADIO_SS_PIN (P1.1):   Chip Select (controlled by hal_gpio)
 */

#include "hal_spi.h"
#include "Config_CSI20.h"
#include "hal_systick.h"
#include "log_control.h"
#include <string.h>

/*======================================================================
 * Private Variables
 *======================================================================*/

/*======================================================================
 * Public Functions
 *======================================================================*/

/**
 * @brief Initialize SPI peripheral (CSI20)
 * 
 * Configures CSI20 module for SPI communication with SX1262.
 * Settings:
 *   - Mode: SPI Mode 0 (CPOL=0, CPHA=0)
 *   - Speed: 2 MHz (8MHz MCU / 4 prescaler)
 *   - Data width: 8 bits
 *   - MSB first
 *   - Single transfer mode
 *
 * @return 0 on success, -1 on error
 */
int hal_spi_init(void)
{
    /* Initialize CSI20 - generated by Smart Config */
    R_Config_CSI20_Create();
    
    /* Start CSI20 module */
    R_Config_CSI20_Start();
    
    /* Disable interrupt for polling mode */
    CSIMK20 = 1U;
    
    return 0;
}

/**
 * @brief Deinitialize SPI peripheral
 *
 * @return 0 on success
 */
int hal_spi_deinit(void)
{
    R_Config_CSI20_Stop();
    return 0;
}

/**
 * @brief Transfer single byte via SPI
 *
 * Sends one byte and receives response in full duplex mode.
 * This is blocking call - waits until transfer complete.
 *
 * @param data Byte to send
 * @return Received byte
 */
uint8_t hal_spi_transfer(uint8_t data)
{
    uint8_t rx_data;
    
    /* Clear interrupt flag */
    CSIIF20 = 0U;
    
    /* Write data to start transfer */
    SIO20 = data;
    
    /* Wait for transfer to complete (Interrupt flag set) */
    /* Since interrupts are masked, the flag will still be set but no ISR will run */
    while (CSIIF20 == 0U);
    
    /* Read received data */
    rx_data = SIO20;
    
    return rx_data;
}

/**
 * @brief Write buffer via SPI
 *
 * Sends data buffer via SPI. Response is discarded.
 *
 * @param buf Pointer to buffer containing data to send
 * @param len Buffer length (max SPI_MAX_BUFFER_SIZE)
 * @return 0 on success, -1 on error
 */
int hal_spi_write(const uint8_t *buf, uint16_t len)
{
    uint16_t i;
    
    if (buf == NULL || len == 0) {
        return -1;
    }
    
    for (i = 0; i < len; i++) {
        hal_spi_transfer(buf[i]);
    }
    
    return 0;
}

/**
 * @brief Read buffer via SPI
 *
 * Receives data from SPI by sending dummy bytes (0xFF).
 *
 * @param buf Pointer to buffer to store received data
 * @param len Buffer length (max SPI_MAX_BUFFER_SIZE)
 * @return 0 on success, -1 on error
 */
int hal_spi_read(uint8_t *buf, uint16_t len)
{
    uint16_t i;
    
    if (buf == NULL || len == 0) {
        return -1;
    }
    
    for (i = 0; i < len; i++) {
        buf[i] = hal_spi_transfer(0xFF);
    }
    
    return 0;
}

/**
 * @brief Write and read buffer via SPI
 *
 * Full duplex SPI transfer - sends data and receives response simultaneously.
 * Useful for reading SX1262 status while sending commands.
 *
 * @param tx_buf Pointer to transmit buffer
 * @param rx_buf Pointer to receive buffer
 * @param len Length of transfer (max SPI_MAX_BUFFER_SIZE)
 * @return 0 on success, -1 on error
 */
int hal_spi_transfer_buffer(const uint8_t *tx_buf, uint8_t *rx_buf, uint16_t len)
{
    uint16_t i;
    
    if (tx_buf == NULL || rx_buf == NULL || len == 0) {
        return -1;
    }
    
    for (i = 0; i < len; i++) {
        rx_buf[i] = hal_spi_transfer(tx_buf[i]);
    }
    
    return 0;
}

/**
 * @brief Get SPI status
 *
 * @return 1 if busy, 0 if idle
 */
int hal_spi_is_busy(void)
{
    /* CSI20 is blocking, so always return 0 (not busy after call returns) */
    return 0;
}

/*======================================================================
 * End of hal_spi.c
 *======================================================================*/
