/*
 * File: hal_spi.c
 * Description: SPI Hardware Abstraction Layer for SX1262
 * Module: CSI20 (Serial Array Unit, Channel 0)
 * Speed: 2 MHz (8MHz MCU / 4 prescaler)
 * 
 * Pin assignments (from Smart Config Pin.h):
 * - RADIO_SCK_PIN (P1.5):  Clock
 * - RADIO_MOSI_PIN (P1.3): Master Out, Slave In (SO20)
 * - RADIO_MISO_PIN (P1.4): Master In, Slave Out (SI20)
 * - RADIO_SS_PIN (P1.1):   Chip Select (controlled by hal_gpio)
 */

#include "hal_spi.h"
#include "../smc_gen/Config_CSI20/Config_CSI20.h"
#include <string.h>

/*======================================================================
 * Private Variables
 *======================================================================*/

/* Buffer for SPI transfer */
static uint8_t spi_rx_buffer[SPI_MAX_BUFFER_SIZE];
static uint8_t spi_tx_buffer[SPI_MAX_BUFFER_SIZE];

/*======================================================================
 * Public Functions
 *======================================================================*/

/**
 * @brief Initialize SPI peripheral (CSI20)
 * 
 * Configures CSI20 module for SPI communication with SX1262.
 * Settings:
 *   - Mode: SPI Mode 0 (CPOL=0, CPHA=0)
 *   - Speed: 2 MHz (8MHz MCU / 4 prescaler)
 *   - Data width: 8 bits
 *   - MSB first
 *   - Single transfer mode
 *
 * @return 0 on success, -1 on error
 */
int hal_spi_init(void)
{
    /* Initialize CSI20 - generated by Smart Config */
    R_Config_CSI20_Create();
    
    /* Start CSI20 module */
    R_Config_CSI20_Start();
    
    return 0;
}

/**
 * @brief Deinitialize SPI peripheral
 *
 * @return 0 on success
 */
int hal_spi_deinit(void)
{
    R_Config_CSI20_Stop();
    return 0;
}

/**
 * @brief Transfer single byte via SPI
 *
 * Sends one byte and receives response in full duplex mode.
 * This is blocking call - waits until transfer complete.
 *
 * @param data Byte to send
 * @return Received byte
 */
uint8_t hal_spi_transfer(uint8_t data)
{
    MD_STATUS status;
    uint8_t tx_buf = data;
    uint8_t rx_buf = 0;
    
    /* Perform SPI transfer */
    status = R_Config_CSI20_Send_Receive(&tx_buf, 1, &rx_buf);
    
    if (status != MD_OK) {
        return 0;
    }
    
    return rx_buf;
}

/**
 * @brief Write buffer via SPI
 *
 * Sends data buffer via SPI. Response is discarded.
 *
 * @param buf Pointer to buffer containing data to send
 * @param len Buffer length (max SPI_MAX_BUFFER_SIZE)
 * @return 0 on success, -1 on error
 */
int hal_spi_write(const uint8_t *buf, uint16_t len)
{
    MD_STATUS status;
    
    if (buf == NULL || len == 0 || len > SPI_MAX_BUFFER_SIZE) {
        return -1;
    }
    
    /* Copy data to tx buffer */
    memcpy(spi_tx_buffer, buf, len);
    
    /* Clear rx buffer */
    memset(spi_rx_buffer, 0, len);
    
    /* Perform SPI transfer */
    status = R_Config_CSI20_Send_Receive(spi_tx_buffer, len, spi_rx_buffer);
    
    if (status != MD_OK) {
        return -1;
    }
    
    return 0;
}

/**
 * @brief Read buffer via SPI
 *
 * Receives data from SPI by sending dummy bytes (0xFF).
 *
 * @param buf Pointer to buffer to store received data
 * @param len Buffer length (max SPI_MAX_BUFFER_SIZE)
 * @return 0 on success, -1 on error
 */
int hal_spi_read(uint8_t *buf, uint16_t len)
{
    MD_STATUS status;
    
    if (buf == NULL || len == 0 || len > SPI_MAX_BUFFER_SIZE) {
        return -1;
    }
    
    /* Fill tx buffer with dummy data (0xFF) */
    memset(spi_tx_buffer, 0xFF, len);
    
    /* Perform SPI transfer */
    status = R_Config_CSI20_Send_Receive(spi_tx_buffer, len, spi_rx_buffer);
    
    if (status != MD_OK) {
        return -1;
    }
    
    /* Copy received data to output buffer */
    memcpy(buf, spi_rx_buffer, len);
    
    return 0;
}

/**
 * @brief Write and read buffer via SPI
 *
 * Full duplex SPI transfer - sends data and receives response simultaneously.
 * Useful for reading SX1262 status while sending commands.
 *
 * @param tx_buf Pointer to transmit buffer
 * @param rx_buf Pointer to receive buffer
 * @param len Length of transfer (max SPI_MAX_BUFFER_SIZE)
 * @return 0 on success, -1 on error
 */
int hal_spi_transfer_buffer(const uint8_t *tx_buf, uint8_t *rx_buf, uint16_t len)
{
    MD_STATUS status;
    
    if (tx_buf == NULL || rx_buf == NULL || len == 0 || len > SPI_MAX_BUFFER_SIZE) {
        return -1;
    }
    
    /* Copy tx data to buffer */
    memcpy(spi_tx_buffer, tx_buf, len);
    
    /* Clear rx buffer */
    memset(spi_rx_buffer, 0, len);
    
    /* Perform SPI transfer */
    status = R_Config_CSI20_Send_Receive(spi_tx_buffer, len, spi_rx_buffer);
    
    if (status != MD_OK) {
        return -1;
    }
    
    /* Copy received data to output buffer */
    memcpy(rx_buf, spi_rx_buffer, len);
    
    return 0;
}

/**
 * @brief Get SPI status
 *
 * @return 1 if busy, 0 if idle
 */
int hal_spi_is_busy(void)
{
    /* CSI20 is blocking, so always return 0 (not busy after call returns) */
    return 0;
}

/*======================================================================
 * End of hal_spi.c
 *======================================================================*/
